name: Push to main branch

on:
  push:
    branches:
      - main

jobs:
  process-push:
    name: Execute push on main
    runs-on: ubuntu-latest
    permissions:
      contents: write # this must be set to 'write' in order for the workflow to add a tag
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Determine application version
        id: version
        uses: paulhatch/semantic-version@v5.4.0
      - name: Tag the branch with the application version
        uses: rickstaa/action-create-tag@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{steps.version.outputs.version_tag}}
      - name: Show the tag value
        run: 'echo This is the tag value that any job or step in the workflow can now use: ${{steps.version.outputs.version_tag}}'
  