name: Push to feature branch

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  process-push:
    name: Execute push on feature branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Show me you are working
        run: echo "This is the 'Push to feature branch'!!!"
